### PR TITLE
Drop PHP-7.2 and PHP-7.3 version supports

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- According to the [official PHP website](https://www.php.net/eol.php), it's time to drop the `PHP 7.2` and `PHP 7.3` versions.
- Letting the PHP package require `PHP 7.4` and `PHP 8.0+` versions.

### CODE REVIEW

**Review by odan — APPROVED** [review]

**Comment by odan** [comment]
I think we can drop PHP 7 support and move to PHP 8 now.

**Comment by peter279k** [comment]
@odan. I completely drop `PHP 7.4` version support and using the `PHP 8.0` version requirement at least.

I also run the `vendor/bin/php-cs-fixer fix --format=txt --verbose --diff --config=.cs.php` to fix the coding style issues.

**Comment by odan** [comment]
The latest version of PhpCsFixer has a new default value for `global_namespace_import = true`.  We should set it to false in `.cs.php`. `'global_namespace_import' => false,`

**Comment by odan** [comment]
I will merge it and fix the CS afterwards.

**Pull request merged**
